import asyncio
from html.parser import HTMLParser
from pathlib import Path

import httpx

_DATA_VERSION_API = (
    "https://minecraft.wiki/api.php?action=parse&page=Data_version&prop=text&format=json&formatversion=2"
)

# Java version requirements — update this table when Minecraft raises its Java floor,
# then re-run `just gen-version-table` to rebuild version_data.py.
# Each entry: (min_data_version, java_feature_version), sorted descending.
_JAVA_VERSION_TABLE: list[tuple[int, int]] = [
    (4764, 25),  # 26.1 snapshot 1  — Java 25
    (3827, 21),  # 24w14a / 1.20.5  — Java 21
    (2848, 17),  # 1.18 Pre-release 2  — Java 17
    (2714, 16),  # 21w19a / 1.17  — Java 16
    (1122, 8),  # 17w13a / 1.12  — Java 8
]


# Grabs a version table from the Minecraft wiki to build a table of version str to int.
# e.g. "26.1 snapshot 1" -> 4764
# used for reading versions from JARs and for processing different versions
class _VersionTableParser(HTMLParser):
    def __init__(self) -> None:
        super().__init__()
        self._in_table = False
        self._in_row = False
        self._in_td = False
        self._td_index = 0
        self._version_text = ""
        self._dv_text = ""
        self.result: dict[int, str] = {}

    def handle_starttag(self, tag: str, attrs: list[tuple[str, str | None]]) -> None:
        attr_dict = dict(attrs)
        if tag == "table" and "wikitable" in (attr_dict.get("class") or ""):
            self._in_table = True
        elif self._in_table and tag == "tr":
            self._in_row = True
            self._td_index = 0
            self._version_text = ""
            self._dv_text = ""
        elif self._in_table and self._in_row and tag == "td":
            self._in_td = True

    def handle_endtag(self, tag: str) -> None:
        if tag == "table":
            self._in_table = False
        elif self._in_table and tag == "td":
            self._in_td = False
            self._td_index += 1
        elif self._in_table and self._in_row and tag == "tr":
            self._in_row = False
            version = self._version_text.strip().removeprefix("Java Edition ")
            try:
                dv = int(self._dv_text.strip())
                if version:
                    self.result[dv] = version
            except ValueError:
                pass

    def handle_data(self, data: str) -> None:
        if self._in_td:
            if self._td_index == 0:
                self._version_text += data
            elif self._td_index == 1:
                self._dv_text += data


_OUT = Path(__file__).parent.parent / "src" / "server" / "version_data.py"


async def main() -> None:
    print("Fetching data versions from Minecraft wiki...", flush=True)
    async with httpx.AsyncClient() as client:
        r = await client.get(_DATA_VERSION_API, timeout=30)
        r.raise_for_status()
        html: str = r.json()["parse"]["text"]
    parser = _VersionTableParser()
    parser.feed(html)
    version_map = parser.result
    print(f"  {len(version_map)} versions found", flush=True)

    lines: list[str] = [
        "# Generated by scripts/build_version_table.py — run `just gen-version-table` to update.",
        "",
        "# Maps Minecraft data version integers to release strings, e.g. {3700: '1.20.4'}.",
        "VERSION_MAP: dict[int, str] = {",
    ]
    for dv in sorted(version_map, reverse=True):
        lines.append(f'    {dv}: "{version_map[dv]}",')
    lines.append("}")
    lines.append("")
    lines.append("# Maps minimum data version thresholds to required Java feature versions.")
    lines.append("# Sorted descending — first match wins.")
    lines.append("JAVA_VERSION_TABLE: list[tuple[int, int]] = [")
    for threshold, java_ver in _JAVA_VERSION_TABLE:
        comment_ver = version_map.get(threshold, "")
        suffix = f"  # {comment_ver} — Java {java_ver}" if comment_ver else f"  # Java {java_ver}"
        lines.append(f"    ({threshold}, {java_ver}),{suffix}")
    lines.append("]")
    lines.append("")

    _OUT.write_text("\n".join(lines))
    print(f"  Written {_OUT.relative_to(Path(__file__).parent.parent)}", flush=True)


if __name__ == "__main__":
    asyncio.run(main())
